apiVersion: batch/v1
kind: CronJob
metadata:
  name: mail-utility-job
spec:
  schedule: "0 10 * * 1,3,5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: mail-utility
            image: localhost:32000/mail_utility
            imagePullPolicy: Always
            env:
            - name: TZ
              value: Europe/London
            - name: DATABASE_IP
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: endpoint-url
            - name: MJ_APIKEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: mail-jet-secret
                  key: MJ_APIKEY_PUBLIC
            - name: MJ_APIKEY_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: mail-jet-secret
                  key: MJ_APIKEY_PRIVATE
            - name: MJ_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mail-jet-secret
                  key: MJ_EMAIL
            - name: DATABASE_ADAPTER_USER
              valueFrom:
                secretKeyRef:
                  name: access-server-secret
                  key: username
            - name: DATABASE_ADAPTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: access-server-secret
                  key: secret
          restartPolicy: Never