apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-adapter
spec:
  replicas: 3 # Number of replicas you want to run
  selector:
    matchLabels:
      app: database-adapter
  template:
    metadata:
      labels:
        app: database-adapter
    spec:
      containers:
      - name: database-adapter
        image: icroboticssociety/db-adapter
        ports:
        - containerPort: 8000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        env:
        - name: TZ
          value: Europe/London
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: access-server-secret
              key: secret
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: access-server-secret
              key: env
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: access-server-secret
              key: username
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: imperial-secret
              key: api_key
        - name: MEME_DB
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: meme-db

        volumeMounts:
          - name: postgres-ini 
            mountPath: /app/postgres.ini
            subPath: postgres.ini
            readOnly: true
          - name: printer-config 
            mountPath: /app/printer_config.json
            subPath: printer_config.json
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60

      volumes:
        - name: postgres-ini 
          secret:
            secretName: postgres-ini-secret 
        - name: printer-config 
          configMap:
            name: printer-config
            items:
              - key: printer_config
                path: printer_config.json

---
apiVersion: v1
kind: Service
metadata:
  name: database-adapter-service
spec:
  selector:
    app: database-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
