CREATE TABLE IF NOT EXISTS Access
(
    ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    CANPRINT VARCHAR(10) DEFAULT 'FALSE',
    CANLASERCUT VARCHAR(10) DEFAULT 'FALSE',
    VALID VARCHAR(10) DEFAULT 'FALSE'
);
