CREATE TABLE IF NOT EXISTS Access
(
    ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    SHORTCODE VARCHAR(10) DEFAULT '',
    -- CID VARCHAR(10) DEFAULT '',
    CANPRINT VARCHAR(10) DEFAULT 'FALSE',
    CANLASERCUT VARCHAR(10) DEFAULT 'FALSE',
    VALID VARCHAR(10) DEFAULT 'FALSE'
);
