apiVersion: apps/v1
kind: Deployment
metadata:
  name: notion-manager
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: notion-manager
  template:
    metadata:
      labels:
        app: notion-manager
    spec:
      containers:
      - name: notion-manager
        image: localhost:32000/notion_manager
        ports:
        - containerPort: 8000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        env:
        - name: TZ
          value: Europe/London



---
apiVersion: v1
kind: Service
metadata:
  name: notion-manager-service
spec:
  selector:
    app: notion-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30003
  type: NodePort
