apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrsbot-printer-queue-manager-deployment
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrsbot-printer-queue-manager
  template:
    metadata:
      labels:
        app: icrsbot-printer-queue-manager
    spec:
      containers:
        - name: icrsbot-printer-queue-manager
          image: localhost:32000/icrsbot-printer-queue-manager # Replace with your Python Docker image and tag
          ports:
            - containerPort: 5000 # Port your Python application is listening on
          imagePullPolicy: "Always"
          env:
            - name: TZ
              value: Europe/London
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: print-queue-default-user
                  key: host
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: print-queue-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: print-queue-default-user
                  key: password
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: print-queue-default-user
                  key: port
          volumeMounts:
            - name: printer-config
              mountPath: /app/endpoints.json
              subPath: endpoints.json
              readOnly: true
            - name: rabbitmq-config
              mountPath: /app/rabbitmq.json
              subPath: rabbitmq.json

      volumes:
        - name: printer-config
          configMap:
            name: printer-config
            items:
              - key: printer_config
                path: endpoints.json
        - name: rabbitmq-config
          secret:
            secretName: rabbitmq-secret
            items:
              - key: rabbitmq.json
                path: rabbitmq.json

