apiVersion: apps/v1
kind: Deployment
metadata:
  name: icrs-access-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: icrs-access
  template:
    metadata:
      labels:
        app: icrs-access
    spec:
      containers:
      - name: icrs-access
        image: localhost:32000/icrs-access  # Replace with your Python Docker image and tag
        ports:
        - containerPort: 8888  # Port your Python application is listening on
        imagePullPolicy: "Always"
        volumeMounts:
          - name: postgres-ini 
            mountPath: /app/postgres.ini
            subPath: postgres.ini
            readOnly: true
      volumes:
        - name: postgres-ini 
          secret:
            secretName: postgres-ini-secret 


---
apiVersion: v1
kind: Service
metadata:
  name: icrs-access-service
spec:
  selector:
    app: icrs-access
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30001  # Change this to the desired external port
      targetPort: 8888
  type: NodePort
