services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - grafana
    develop:
      watch:
        - action: sync
          path: ./nginx.conf
          target: /etc/nginx/nginx.conf
