services:
  nginx:
    build:
      context: .
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./directory.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
    depends_on:
      - grafana
    develop:
      watch:
        - action: rebuild
          path: ./nginx.conf
          target: /etc/nginx/nginx.conf
        - action: rebuild
          path: ./directory.html
          target: /usr/share/nginx/html/index.html
