events {
  worker_connections  4096;  ## Default: 1024
}

http{
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  upstream pgadmin {
    server pgadmin-service.pgadmin.svc.cluster.local:80;
  }

  upstream k8s {
    server kubernetes-dashboard.kube-system.svc.cluster.local:443;
  }

  upstream partdb {
    server partdb.default.svc.cluster.local:80;
  }

  upstream grafana {
    server grafana.grafana.svc.cluster.local:3000;
  }

  upstream access_server {
    server access-server.default.svc.cluster.local:8000;
  }

  upstream printer_scanner_router {
    server printer-scanner-router.default.svc.cluster.local:80;
  }

  server {
    listen 80;
    root /usr/share/nginx/www;
    index index.html index.htm;

    location /dashboard/ {
      rewrite ^/dashboard/(.*) $1/ redirect;
      proxy_pass http://k8s;
    }

    location /grafana/ {
      rewrite  ^/grafana/(.*)  /$1 break;
      proxy_set_header Host $http_host;
      proxy_pass http://grafana;
    }

    location /partdb/ {
      rewrite  ^/partdb/(.*)  /$1 break;
      proxy_set_header X-Forwarded-Prefix \"/partdb/\";
      proxy_pass http://partdb;
    }

    location /api/printer/router/ {
      rewrite  ^/api/printer/router/(.*)  /$1 break;
      proxy_set_header Host $http_host;
      proxy_pass http://printer_scanner_router;
    }

    location /api/access/ {
      rewrite  ^/api/access/(.*)  /$1 break;
      proxy_set_header Host $http_host;
      proxy_pass http://access_server;
    }

    location /pgadmin/ {
      rewrite  ^/pgadmin/(.*)  /pgadmin/$1 break;
      proxy_set_header Host $http_host; 
      proxy_pass http://pgadmin;
    }

  }
}
