server {
    listen 80;
    default_type text/plain;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://database-adapter-service.default.svc.cluster.local/; 
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
