server {
    # TODO envsubst
    listen 80;
    # server_name ${NGINX_MY_SERVER_NAME};
    default_type text/plain;
    # location / { 
    #     return 200 'OK\n'; 
    #     }
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8888/; # TODO: Put API IP and PORT here 
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
    # location / {
    # }
}