on:
  push:
    branches:
    - master
    paths:
      - 'bambu_printer_gateway/**'
      - '.github/workflows/bambu_printer_gateway.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        run: |
          cd bambu_printer_gateway
          ./docker_build.sh ${GITHUB_SHA}
          kubectl set image deployments/icrsbot icrsbot=localhost:32000/icrsbot:${GITHUB_SHA}
