on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Build
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/icrs_security:${GITHUB_SHA} .
      
      