on:
  push:
    branches:
    - master
    paths:
      - 'printer_scanner_router/**'
      - '.github/workflows/printer_scanner_router.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        run: |
          cd printer_scanner_router
          ./docker_build.sh ${GITHUB_SHA}
          kubectl set image deployments/icrsbot-printer-queue-manager-deployment icrsbot-printer-queue-manager=localhost:32000/icrsbot-printer-queue-manager:${GITHUB_SHA}
