on:
  push:
    branches:
    - main
    paths:
      - 'bambu_printer_gateway/**'
      - '.github/workflows/printer_gateway.yml'

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

  update_deployments:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Deploy to remote server
        run: |
          cd bambu_printer_gateway
          ./docker_build.sh ${GITHUB_SHA}
          ./deploy.sh ${GITHUB_SHA}

