apiVersion: apps/v1
kind: Deployment
metadata:
  name: printer-scanner-router
spec:
  replicas: 1 # Number of replicas you want to run
  selector:
    matchLabels:
      app: printer-scanner-router
  template:
    metadata:
      labels:
        app: printer-scanner-router
    spec:
      containers:
      - name: printer-scanner-router
        image: localhost:32000/printer_scanner_router
        ports:
        - containerPort: 8000  # Port your Python application is listening on
        imagePullPolicy: "Always"
        env:
        - name: TZ
          value: Europe/London
        volumeMounts:
          - name: printer-config 
            mountPath: /app/printer_config.json
            subPath: printer_config.json
            readOnly: true
      volumes:
        - name: printer-config 
          configMap:
            name: printer-config
            items:
              - key: printer_config
                path: printer_config.json


---
apiVersion: v1
kind: Service
metadata:
  name: printer-scanner-router-service
spec:
  selector:
    app: printer-scanner-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 33000
  type: NodePort
